// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjgysAjtsHAsmWeBva4T2LAQw_PleTJ9c',
    appId: '1:94546898722:web:fe17bcefdbaaf32b547f7b',
    messagingSenderId: '94546898722',
    projectId: 'flutter-expense-journey',
    authDomain: 'flutter-expense-journey.firebaseapp.com',
    storageBucket: 'flutter-expense-journey.appspot.com',
    measurementId: 'G-H3YKY2QGZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuljFtALsf-qt7LRlVOhdVomt4TwLX-8A',
    appId: '1:94546898722:android:50db9e2058407639547f7b',
    messagingSenderId: '94546898722',
    projectId: 'flutter-expense-journey',
    storageBucket: 'flutter-expense-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYiEMWquxPs7DZIeW3jDdyiH7KJe1_j8',
    appId: '1:94546898722:ios:3551044a079350f6547f7b',
    messagingSenderId: '94546898722',
    projectId: 'flutter-expense-journey',
    storageBucket: 'flutter-expense-journey.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYiEMWquxPs7DZIeW3jDdyiH7KJe1_j8',
    appId: '1:94546898722:ios:3551044a079350f6547f7b',
    messagingSenderId: '94546898722',
    projectId: 'flutter-expense-journey',
    storageBucket: 'flutter-expense-journey.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjgysAjtsHAsmWeBva4T2LAQw_PleTJ9c',
    appId: '1:94546898722:web:a092068242f1f306547f7b',
    messagingSenderId: '94546898722',
    projectId: 'flutter-expense-journey',
    authDomain: 'flutter-expense-journey.firebaseapp.com',
    storageBucket: 'flutter-expense-journey.appspot.com',
    measurementId: 'G-SZ2C02CYJR',
  );

}